// Exportable products: a formatted SITREP (markdown) and a COP data dump (JSON).
import type { CountryRisk, IntelEvent, MarketTick, ThreatState } from '../types'

interface ReportInput {
  brief: string
  threat: ThreatState
  events: IntelEvent[]
  countryRisk: CountryRisk[]
  markets: MarketTick[]
  generatedAt: number
}

function dtg(ts: number): string {
  // Date-Time Group-ish stamp (UTC).
  return new Date(ts).toISOString().replace('T', ' ').slice(0, 19) + 'Z'
}

export function buildSITREP(input: ReportInput): string {
  const { brief, threat, events, countryRisk, generatedAt } = input
  const top = [...events]
    .filter((e) => e.severity >= 50)
    .sort((a, b) => b.severity - a.severity)
    .slice(0, 15)

  const lines: string[] = []
  lines.push('# DRTC SITUATION REPORT')
  lines.push('CLASSIFICATION: UNCLASSIFIED // FOR DEMONSTRATION ONLY // OSINT')
  lines.push(`DTG: ${dtg(generatedAt)}`)
  lines.push('')
  lines.push(`## 1. ASSESSMENT — CONDITION ${threat.level} (${threat.label})`)
  lines.push(`Global Threat Index: ${threat.index}/100 (trend ${threat.trend}).`)
  lines.push('')
  lines.push(brief)
  lines.push('')
  lines.push('## 2. PRIORITY TRACKS')
  if (top.length) {
    top.forEach((e, i) =>
      lines.push(
        `${String(i + 1).padStart(2, '0')}. [SEV ${e.severity}] ${e.title} — ${e.summary} (${e.source}, ${dtg(e.timestamp)})`,
      ),
    )
  } else {
    lines.push('No tracks at or above severity 50.')
  }
  lines.push('')
  lines.push('## 3. INSTABILITY POSTURE (DRTC-CII)')
  countryRisk
    .slice(0, 10)
    .forEach((c, i) =>
      lines.push(
        `${String(i + 1).padStart(2, '0')}. ${c.name} (${c.iso}) — ${c.score} · ${c.drivers.join(', ')}`,
      ),
    )
  lines.push('')
  lines.push('---')
  lines.push(
    'Generated by DRTC. Sources: USGS, NASA EONET, NOAA SWPC, GDELT, wheretheiss.at, CoinGecko.',
  )
  return lines.join('\n')
}

export function buildCOP(input: ReportInput): string {
  return JSON.stringify(
    {
      classification: 'UNCLASSIFIED//FOR DEMONSTRATION ONLY//OSINT',
      generatedAt: dtg(input.generatedAt),
      threat: input.threat,
      countryRisk: input.countryRisk,
      markets: input.markets,
      events: input.events.map((e) => ({
        id: e.id,
        source: e.source,
        category: e.category,
        severity: e.severity,
        title: e.title,
        summary: e.summary,
        lat: e.lat,
        lng: e.lng,
        timestamp: new Date(e.timestamp).toISOString(),
      })),
    },
    null,
    2,
  )
}

export function downloadText(filename: string, content: string, mime = 'text/plain') {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  URL.revokeObjectURL(url)
}
